# Generated by Django 6.0.1 on 2026-01-07 19:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='activities.activity')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'event',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text="User's rating of the event (1-5 stars)", null=True)),
                ('feedback', models.TextField(blank=True, help_text='Optional text feedback about the event')),
            ],
            options={
                'verbose_name': 'Event Participation',
                'verbose_name_plural': 'Event Participations',
                'db_table': 'event_participation',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_value', models.CharField(choices=[('LIKE', 'Like'), ('NEUTRAL', 'Neutral'), ('DISLIKE', 'Dislike')], default='NEUTRAL', help_text='Like/Neutral/Dislike - defaults to Neutral if not specified', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Interaction',
                'verbose_name_plural': 'User Interactions',
                'db_table': 'user_interaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRequirements',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='requirements', serialize=False, to='events.event')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('PNS', 'Prefer Not to Say'), ('O', 'Other')], help_text='Required gender for event participation (optional)', max_length=3, null=True)),
                ('min_age', models.IntegerField(blank=True, help_text='Minimum age for participation', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('max_age', models.IntegerField(blank=True, help_text='Maximum age for participation', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('required_proficiency', models.CharField(blank=True, choices=[('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced'), ('COMP', 'Competitive')], help_text='Minimum required proficiency level', max_length=4, null=True)),
            ],
            options={
                'verbose_name': 'Event Requirements',
                'verbose_name_plural': 'Event Requirements',
                'db_table': 'event_requirements',
            },
        ),
    ]
