# Generated by Django 6.0 on 2025-12-26 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='joined_events', through='events.EventParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['joined_at'], name='events_even_joined__92f422_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('user', 'event')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_time'], name='events_even_start_t_c2d277_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['activity', 'start_time'], name='events_even_activit_243590_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['location'], name='events_even_locatio_0ae1f4_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by'], name='events_even_created_95418c_idx'),
        ),
    ]
