# Generated by Django 6.0.1 on 2026-01-07 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('metabolic_demand', models.FloatField(help_text='Normalized [0–1] physical energy expenditure', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('neurocognitive_precision', models.FloatField(help_text='Normalized [0–1] cognitive complexity', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('risk_modulation', models.FloatField(help_text='Normalized [0–1] injury / risk exposure', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('kinesthetic_intelligence', models.FloatField(help_text='Normalized [0–1] motor coordination demand', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('environmental_dependency', models.FloatField(help_text='Normalized [0–1] dependence on environment', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('collaborative_dynamics', models.FloatField(help_text='Normalized [0–1] social/team dependence', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'db_table': 'activity',
                'ordering': ['name'],
            },
        ),
    ]
